import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:sentery_app/core/database/daos/report_dao.dart';
import 'package:sentery_app/core/utils/currency_formatter.dart';
import 'package:sentery_app/core/database/app_database.dart';

class ReportPdfService {
  Future<Uint8List> generateMonthlyReportPdf(FullMonthlyReport report, DateTime month) async {
    final pdf = pw.Document();
    final monthLabel = '${_monthName(month.month)} ${month.year}';

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('Sentery Shop', style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
            pw.Text('Monthly Report - $monthLabel', style: const pw.TextStyle(fontSize: 13)),
            pw.SizedBox(height: 20),

            _sectionTitle('Sales'),
            _row('Wholesale Sales', report.wholesaleSales),
            _row('Retail Sales', report.retailSales),
            _row('Total Sales', report.totalSales, isBold: true),
            pw.SizedBox(height: 4),
            _row('Cash Received', report.cashReceived),
            _row('Online Received', report.onlineReceived),
            _row('Credit Given', report.creditGiven),
            pw.SizedBox(height: 16),

            _sectionTitle('Purchases'),
            _row('Total Purchases', report.totalPurchases, isBold: true),
            _row('Cash Paid', report.cashPaid),
            _row('Online Paid', report.onlinePaid),
            _row('Credit Taken', report.creditTaken),
            pw.SizedBox(height: 16),

            _sectionTitle('Profit'),
            _row('Gross Profit', report.grossProfit, isBold: true),
            pw.SizedBox(height: 16),

            _sectionTitle('Outstanding Balances'),
            _row('We Owe Suppliers', report.supplierOutstanding),
            _row('Wholesalers Owe Us', report.wholesalerOutstanding),
            _row('Customers Owe Us', report.customerOutstanding),
            _row('Net Outstanding', report.netOutstanding, isBold: true),
            pw.SizedBox(height: 16),

            _sectionTitle('Shop Value'),
            _row('Stock Value (Cost)', report.stockValueAtCost),
            _row('Stock Value (Retail)', report.stockValueAtRetail),
            _row('Total Assets', report.totalAssets),
            _row('Total Liabilities', report.totalLiabilities),
            _row('Net Shop Value', report.netShopValue, isBold: true),

            pw.Spacer(),
            pw.Divider(),
            pw.Center(
              child: pw.Text('Generated by Sentery Shop Management', style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700)),
            ),
          ],
        ),
      ),
    );

    return pdf.save();
  }

  pw.Widget _sectionTitle(String text) => pw.Padding(
    padding: const pw.EdgeInsets.only(bottom: 6),
    child: pw.Text(text.toUpperCase(), style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey700)),
  );

  pw.Widget _row(String label, double value, {bool isBold = false}) => pw.Padding(
    padding: const pw.EdgeInsets.symmetric(vertical: 2),
    child: pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(label, style: pw.TextStyle(fontSize: 10, fontWeight: isBold ? pw.FontWeight.bold : pw.FontWeight.normal)),
        pw.Text(CurrencyFormatter.format(value.abs()), style: pw.TextStyle(fontSize: 10, fontWeight: isBold ? pw.FontWeight.bold : pw.FontWeight.normal)),
      ],
    ),
  );

  String _monthName(int m) =>
      const ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][m - 1];

  Future<void> previewMonthlyReport(FullMonthlyReport report, DateTime month) async {
    final bytes = await generateMonthlyReportPdf(report, month);
    await Printing.layoutPdf(onLayout: (format) => bytes);
  }

  Future<void> shareMonthlyReport(FullMonthlyReport report, DateTime month) async {
    final bytes = await generateMonthlyReportPdf(report, month);
    final directory = await getTemporaryDirectory();
    final file = File('${directory.path}/Monthly_Report_${month.year}_${month.month}.pdf');
    await file.writeAsBytes(bytes);
    await Share.shareXFiles(
      [XFile(file.path)],
      text: 'Monthly Shop Report',
    );
  }

  Future<Uint8List> generatePartyStatementPdf({
    required String partyType, 
    required String partyName,
    String? partyPhone,
    required int currentBalancePaisa,
    required List<LedgerEntry> ledgerEntries,
    required List<Invoice> invoices,
  }) async {
    final pdf = pw.Document();
    final dateFmt = (DateTime d) => '${d.day}/${d.month}/${d.year}';

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Sentery Shop', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
                pw.Text('Statement Date: ${dateFmt(DateTime.now())}', style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
            pw.SizedBox(height: 12),
            pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey300)),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Account Statement', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
                      pw.Text(partyName, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                      if (partyPhone != null) pw.Text(partyPhone, style: const pw.TextStyle(fontSize: 10)),
                      pw.Text(_partyTypeLabel(partyType), style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Current Balance', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
                      pw.Text(
                        CurrencyFormatter.formatPaisa(currentBalancePaisa.abs()),
                        style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold,
                            color: currentBalancePaisa >= 0 ? PdfColors.green800 : PdfColors.red800),
                      ),
                      pw.Text(currentBalancePaisa >= 0 ? 'They owe us' : 'We owe them', style: const pw.TextStyle(fontSize: 9)),
                    ],
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 16),
          ],
        ),
        build: (context) => [
          pw.Text('TRANSACTION HISTORY', style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
            cellStyle: const pw.TextStyle(fontSize: 8),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
            headers: ['Date', 'Type', 'Debit', 'Credit', 'Balance'],
            data: ledgerEntries.map((e) => [
              dateFmt(e.entryDate),
              e.entryType,
              e.debit > 0 ? CurrencyFormatter.formatPaisa(e.debit) : '-',
              e.credit > 0 ? CurrencyFormatter.formatPaisa(e.credit) : '-',
              CurrencyFormatter.formatPaisa(e.balanceAfter.abs()),
            ]).toList(),
          ),
          pw.SizedBox(height: 20),
          pw.Text('INVOICE LIST', style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
            cellStyle: const pw.TextStyle(fontSize: 8),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
            headers: ['Invoice #', 'Date', 'Status', 'Total', 'Paid', 'Remaining'],
            data: invoices.map((i) => [
              i.invoiceNumber,
              dateFmt(i.invoiceDate),
              i.status,
              CurrencyFormatter.formatPaisa(i.totalAmount),
              CurrencyFormatter.formatPaisa(i.amountPaid),
              CurrencyFormatter.formatPaisa(i.amountRemaining),
            ]).toList(),
          ),
        ],
        footer: (context) => pw.Center(
          child: pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
        ),
      ),
    );

    return pdf.save();
  }

  String _partyTypeLabel(String type) {
    switch (type) {
      case 'customer': return 'Customer Account';
      case 'wholesaler': return 'Wholesaler Account';
      case 'supplier': return 'Supplier Account';
      default: return type;
    }
  }

  Future<void> previewPartyStatement({
    required String partyType, required String partyName, String? partyPhone,
    required int currentBalancePaisa, required List<LedgerEntry> ledgerEntries, required List<Invoice> invoices,
  }) async {
    final bytes = await generatePartyStatementPdf(
      partyType: partyType, partyName: partyName, partyPhone: partyPhone,
      currentBalancePaisa: currentBalancePaisa, ledgerEntries: ledgerEntries, invoices: invoices,
    );
    await Printing.layoutPdf(onLayout: (format) => bytes);
  }
}
